server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/custody_db
    username: custody_user
    password: custody_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

google:
  oauth:
    client-id:  ${GOOGLE_OAUTH_CLIENT_ID}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    redirect-uri: http://localhost:8087/api/auth/google
